### ISSUE TITLE
Structure flight termination package

### ISSUE THREAD

**Issue by okeneo** [UMUAS/Nav2023-2024#7]
Create and structure the flight termination package. This will include creating the directories, files, documentation and all necessary steps required to initialize the flight termination package.

**Comment by ethernet-gravy** [comment]
I found some information related to python packages at https://realpython.com/python-modules-packages/#python-packages.
From the looks of it, we just need an empty python file called \_\_init\_\_.py in the folder flight_termination. Then, we can define classes within classname.py within that folder. We will then be able to import these classes from the **root directory** using 
```import flight_termination.classname```   or   ```from flight_termination import classname```.
